### ISSUE TITLE
CentOS service creation

### ISSUE THREAD

**Issue by jkochfrontline** [whizz/tyk-cookbook#1]
Hey @whizz, thanks so much for putting this together!  I was having some issues running against CentOS7.  Everything installs correctly, but it looks like the service enable and start launches some rogue processes for both the gateway and dashboard that are not off the actual init scripts.  I'm thinking it might be the init scripts themselves, but not totally sure.

**Comment by whizz** [comment]
Hi there. Centos 7 uses systemd primarily, so the services are created using systemd and have to be controlled thru it, too. 

So something like:

```
# systemctl restart tyk-gateway.service
# systemctl stop tyk-dashboard.service
```

Let me know if that works for you.

**Comment by jkochfrontline** [comment]
Thanks for the quick response!  Yup, the issue was that the wrong provider was being set for the service resource.

This cleared it up:

```
service 'tyk-dashboard' do
  provider Chef::Provider::Service::Init::Redhat
  supports restart: true, reload: false, status: true
  action [:enable, :start]
end
```

**Comment by whizz** [comment]
What Chef version do you run this against? The cookbook works for me as-is on Centos 7.1 using Chef 12.6. I am testing this using kitchen. What problem exactly are you facing?

**Comment by jkochfrontline** [comment]
I'm running chef client 12.6.0 against CentOS 7.1 as well.  If you converge and then login and check the tyk gateway/dashboard service status they are not running.  They processes however are running in the background `ps aux | grep tyk`.

**Comment by whizz** [comment]
Why do you think they are not running? Please remember, these are systemd services. So running:

```
service tyk-gateway status
```

will report that it is not running, but

```
systemctl status tyk-gateway.service
```

should report that it is running.

**Comment by jkochfrontline** [comment]
Ah, doh!  Thanks for the help!  I guess I was getting confused because I wasn't seeing systemctl output the logs specified within the init script (still not seeing them).
